{{- if not .Values.issuer.email -}}
{{- fail "issuer.email is required" -}}
{{- end -}}
{{- if .Values.issuer.dns01.enabled -}}
{{- if not .Values.issuer.dns01.azureDNS.subscriptionID -}}
{{- fail "issuer.dns01.azureDNS.subscriptionID is required when issuer.dns01.enabled is true" -}}
{{- end -}}
{{- if not .Values.issuer.dns01.azureDNS.resourceGroupName -}}
{{- fail "issuer.dns01.azureDNS.resourceGroupName is required when issuer.dns01.enabled is true" -}}
{{- end -}}
{{- if not .Values.issuer.dns01.azureDNS.hostedZoneName -}}
{{- fail "issuer.dns01.azureDNS.hostedZoneName is required when issuer.dns01.enabled is true" -}}
{{- end -}}
{{- if not .Values.issuer.dns01.azureDNS.managedIdentityClientID -}}
{{- fail "issuer.dns01.azureDNS.managedIdentityClientID is required when issuer.dns01.enabled is true" -}}
{{- end -}}
{{- end -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuer.name | quote }}
spec:
  acme:
    server: {{ .Values.issuer.server | quote }}
    email: {{ .Values.issuer.email | quote }}
    privateKeySecretRef:
      name: {{ printf "%s-account-key" .Values.issuer.name | quote }}
    solvers:
      {{- if .Values.issuer.dns01.enabled }}
      - dns01:
          azureDNS:
            subscriptionID: {{ .Values.issuer.dns01.azureDNS.subscriptionID | quote }}
            resourceGroupName: {{ .Values.issuer.dns01.azureDNS.resourceGroupName | quote }}
            hostedZoneName: {{ .Values.issuer.dns01.azureDNS.hostedZoneName | quote }}
            environment: {{ .Values.issuer.dns01.azureDNS.environment | quote }}
            managedIdentity:
              clientID: {{ .Values.issuer.dns01.azureDNS.managedIdentityClientID | quote }}
      {{- else }}
      - http01:
          ingress:
            class: {{ .Values.issuer.ingressClass | quote }}
      {{- end }}
